@host = https://localhost
@port = 7182
@token = CfDJ8LuU4hXVkgNLsS07JvpBoV9c77e4oTRzuBvuv2jd7O6s7wHNETnNiM7ytoyEvow-0RY8_Cn06QO6UD8KhfmVETtW8ipuAvi-HKX2vz7eOQwaMdfzDRrCF2AdZH5S9I3JK1nkvDys1gMejpEhPAQUW4cbXuKMsIR08W_MH6F2kYseehbZ2QsY4sPqK_3O8ugQy5snTFKPMLwhqYSho3z7MiuAW1IScAtynkTwsUH6oV3bU5EK9WbWanCa72Y63btEycaqEXK-WDsolKE7QgQLiio-CZQOcSnfLwhRAu7d7C1Zh5Z6VkGuwbnkLGXmmhHwifRcaLaSqtZHtWAKDIz1dl-XHXlNuHTfIrxO4vOWJwJq8PZzsL09TQyag7VA-bjeiYiVlLGBl7IrhGbs_iAyhJxxn2hHzkbvWXNFoRexBpq-Wz0SyDw5o4H8wMjixHg5je7hdI1NXtH7YVUQ05ZyjTkblk0TSe6l2aIbp6ywJbQ2aBchVCNIDYGJbNGQQnqxD9T94ArNcIoFC2Z3TFhvWzHOyYLDjB0SN7sVQdawUaGsd2XppIoAIhh22ytBNEuugbjPwQH1FoNsH-xjttoNV4fJjqCgEZBW_EE9Sw8tx6zahSTnWiTZw2oSW2xznILWZRg1Y0prNLN7GCTFr00cvy0XaTHqlH6Yp9nCCsJfHx6lFbL9hQq5eh0kx6jd5m_sEgjcsRN8nJAJh3XDxD7AyJE2EuZu4xpUYGfM8FXx0PNNwz_QRWZ3-A2wF7wVDy33FTuLSofJa9pD6TBc98XEWvzN4UTgVer8ytHXCjwsSv7w

@Restaurants.API_HostAddress = https://localhost:7182

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{9fc9098d-57dc-4e13-de17-08dd0001e2d9}
Authorization: Bearer {{token}}
###

Delete {{Restaurants.API_HostAddress}}/api/restaurants/{99531131-463c-4451-d8ef-08dd0648550d}
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Owner2 restaurant2",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@test.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{46a975e8-bc81-48a9-73f7-08dd1684bbe2}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Updated name",
  "Description": "A culinary experience like no other",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes
Content-Type: application/json

{
  "name": "Spaghetti Bolognese",
  "description": "Classic Italian pasta dish with rich meat sauce",
  "price": 12.99,
  "kiloCalories":750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes/1
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{597fa473-16a2-40e1-a11f-08dcd7280581}/dishes
Authorization: Bearer {{token}}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email":"admin@test.com",
  "password":"Password1!"
}

###
Post {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email":"owner2@test.com",
  "password":"Password1!"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality":"French",
  "DateOfBirth": "2010-01-01"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "UserEmail":"owner2@test.com",
  "RoleName":"Owner"
}

###
