@host = https://localhost
@port = 7182
@token = CfDJ8LuU4hXVkgNLsS07JvpBoV8Y01q12oCoxqP9SM2vfpn7eR39luWLHjvffpRFD3p2cKwtiy10139NL_uNjw4_XAGsro_X6UrZFctoB8AeIANF5Eye3WOkJ6DpwxZL_fAruS60SBVvCPxEIsGcw-fABhjPIekIqAodV1W_Aj5_UNfJZYXd3CEknCpsqNQP3PsKjJ7YcB4hQ-ZwzYVcoTprc3ccok1RxdDwsM6o5zLPwtaWK8rGoVWXyjTee4mFeGlaIYMHjOp8h81FcFk2gTp1em0SbnbC6nSjFl8hQQ6ldf7tbeav6i0azeOZ50hen2ZkBZOG2Yz_c2Dd31TYw2q-suqEBVw71a8aIAsWQOpoiDXRFjClEca_nKCGOfLT_qPwczG-E1eeKGfdFHOQLqOqT3mC9qbnRwQQWs5us27uxM3m7Ytd5wSDdD8Ma6vVGh-H7grSKF-WtOynKVhg1Aiu6G4JtsDl8SZCYXDOqMeaOZjSdg7jkjW8jrTky2bDaGr8Uj2H7koZ643-TNBalDRAhaugQCnrrucoWh0SLWJHt9bn13t-0wdz5HVmu7fsnILnUVq-mr8lW3HghlJyW1U9KJSJgy4iElXNiMBHNC24HFL211XZ6B4kM26rjhT2k7AT2G3f67v4DaKg-xeXPYVeuYdcCQXaQABFDjLOQ9fjzEyKv2aDkCePtyuhYfbwe4r17NKvq17QNqF8AYctzqa40ArXOXxGNjCXMsBm1UZGH2Bbx2y-GBHxshv1tU7atlqpN0-Qlr5QCSuYwDHUSNHKCQVJNUbig6gQMrbyKijcgF_U

@Restaurants.API_HostAddress = https://localhost:7182

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{9fc9098d-57dc-4e13-de17-08dd0001e2d9}
Authorization: Bearer {{token}}
###

Delete {{Restaurants.API_HostAddress}}/api/restaurants/{99531131-463c-4451-d8ef-08dd0648550d}
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Owner restaurant",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@test.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{46a975e8-bc81-48a9-73f7-08dd1684bbe2}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Updated name",
  "Description": "A culinary experience like no other",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes
Content-Type: application/json

{
  "name": "Spaghetti Bolognese",
  "description": "Classic Italian pasta dish with rich meat sauce",
  "price": 12.99,
  "kiloCalories":750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes/1
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{597fa473-16a2-40e1-a11f-08dcd7280581}/dishes
Authorization: Bearer {{token}}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email":"user@test.com",
  "password":"Password1!"
}

###
Post {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email":"admin@test.com",
  "password":"Password1!"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality":"French",
  "DateOfBirth": "2010-01-01"
}

###
