@host = https://localhost
@port = 7182
@token =CfDJ8LQ8ZcU6YpRNjYddbjVRv__Y-Fnw0dPVmmlQaYCHqGkLinYSALYp-dQAJ5OG21ViVUgS6clbCS9541glXgV01qOer98e1u3np8u8EXfH_eLVhwS2NOf0tG8bWespmo6usneG16JFgLm7Xh9ebQAD_tmtiaDZm2sgELVE_qDCJwAJ8j4i8s_VW0mf1a9qM27WwfNjJF96IWHBTXqX2Hue7pvoTh7VueebS6YnbLKLYCfllZq8OhgYO5YFs8rOqM7xTMbx4XdpkHI-qKRM2OLMAEm0dycuJkVscWzrPBNlgEKl7cnLpVFYWqsl3z8Lds4B08xj8ml6rTqPCZR_bwrAMrE038q5-v_WXv39XzixUSetoqT_KTLPnhXbPGjqBU-_z-ebEeTDqHukhacPM7shXpjH9IxKFICEWcQWlN--qrkxX2uRbQT-aFwlYjARVsmFM0drjLQ4AqlRnivBGZKLs8Bmj3DRzReXju7cxqZ87RY7_4MZNKyzT0ygdrdUur3Bxe7tKyxu7Mgq9jjgSvCqR_uZiXVelW3s4bhsExYjd5QQrKapRxnfdpT2peTQmlSQT1s_ZtRxoMnmck59G5RoDtIeuDSRyaDJxhrpE017YnyFNVj2NLihv2YBitJTDptj3bq7pTj0Vu3EJZUXsnHZnbaDoeHUDUl_aZoH81bg6TL_-_QLY4M8IPtgYQ0YaLGygqWmnK_b8zvvfMhJReORX2fBJ6WN0MxYyoIdCBfQTYZf-V2PVu8CV_jcof0bOk88x4HA3khA3tA2n1-EM2vsm9dTtyFZklUOoBh1k7XYN8Wp

@Restaurants.API_HostAddress = https://localhost:7182

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{9fc9098d-57dc-4e13-de17-08dd0001e2d9}
Authorization: Bearer {{token}}
###

Delete {{Restaurants.API_HostAddress}}/api/restaurants/{99531131-463c-4451-d8ef-08dd0648550d}
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Owner2 restaurant2",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@test.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{46a975e8-bc81-48a9-73f7-08dd1684bbe2}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name":"Updated name",
  "Description": "A culinary experience like no other",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes
Content-Type: application/json

{
  "name": "Spaghetti Bolognese",
  "description": "Classic Italian pasta dish with rich meat sauce",
  "price": 12.99,
  "kiloCalories":750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes/1
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{597fa473-16a2-40e1-a11f-08dcd7280581}/dishes
Authorization: Bearer {{token}}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{0dcc2410-0f1e-421d-e22b-08dcd8aedf0e}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email":"admin@test.com",
  "password":"Password1!"
}

###
Post {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email":"owner2@test.com",
  "password":"Password1!"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality":"French",
  "DateOfBirth": "2010-01-01"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "UserEmail":"owner2@test.com",
  "RoleName":"Owner"
}

###
